#ifndef CONFIG_H
#define CONFIG_H

#define CFG_HOSTNAME "hbfc"
#define CFG_WIFI_SSID "XXX"
#define CFG_WIFI_PWD "XXX"
#define CFG_MQTT_SERVER "XXX"

#define CFG_PIN_TEMP 19
#define CFG_PIN_FAN_SWITCH_IN 17
#define CFG_PIN_FAN_SWITCH_OUT 21
#define CFG_PIN_FAN_RPM_IN 5
#define CFG_PIN_FAN_RPM_OUT 22
#define CFG_PIN_FAN_PWM_IN 18
#define CFG_PIN_FAN_PWM_OUT 23
#define CFG_PIN_IR_RECEIVE 4
#define CFG_PIN_IR_SEND_OUT 15
#define CFG_PIN_IR_SEND_IN 2

#endif
